version: '3'

services:
  web:
    build: .
    command: bash -c "
      python manage.py migrate
      && python manage.py loaddata fixtures/*
      && python manage.py runserver 0.0.0.0:${WEB_PORT}"
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    restart: always
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app

  postgres:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    env_file:
      - .env.dev

#  db:
#    command:
#      --default-authentication-plugin=mysql_native_password
#      --character-set-server=utf8mb4
#      --collation-server=utf8mb4_0900_as_cs
#    container_name: mysql-local-example
#    image: mysql
#    env_file:
#      - .env
#    ports:
#      - ${MYSQL_PORT}:3306
#    restart: always
#
#  phpmyadmin:
#    container_name: phpmyadmin-local-example
#    image: phpmyadmin/phpmyadmin
#    depends_on:
#      - db
#    ports:
#      - ${PHP_MY_ADMIN_PORT}:80
#    restart: always
#
##  pgadmin:
##    container_name: pgadmin_example
##    image: dpage/pgadmin4
##    environment:
##      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
##      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
##    depends_on:
##      - postgres
##    ports:
##      - ${PG_ADMIN_PORT}:80
##    restart: always

##remove all docker: sudo docker system prune
##put file .env === file docker-compose.yml ( .env file include environ variable)
##run in phpmyadmin
##ALTER USER 'admin' IDENTIFIED WITH mysql_native_password BY 'admin'
